name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  release-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn workspace lib-ts build
      - name: Publish lib-ts to NPM
        run: yarn workspace lib-ts publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
